### ISSUE TITLE
Gradle can't find the plugin

### ISSUE THREAD

**Issue by JohannBlake** [gradle-nexus/publish-plugin#114]
I'm using the latest version of Gradle but when I add the dependency to the root build.gradle file, I get the exception:

Could not resolve all artifacts for configuration ':classpath'.
   > Could not find io.github.gradle-nexus:publish-plugin:1.1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/github/gradle-nexus/publish-plugin/1.1.0/publish-plugin-1.1.0.pom
       - https://repo.maven.apache.org/maven2/io/github/gradle-nexus/publish-plugin/1.1.0/publish-plugin-1.1.0.pom

I was able to resolve it by adding the url to the repository as follows:

```
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
```

**Comment by szpak** [comment]
Yes, the plugin is not (yet) published to Maven Central. However, with the `plugins {}` construction, the plugins repository should be added automatically. The instruction at https://plugins.gradle.org/plugin/io.github.gradle-nexus.publish-plugin for the "legacy" plugin applying (with `buildscript {}`) mentions a need to add `https://plugins.gradle.org/m2/` separately.

Using `repositories {}` (instead of `buildscript {  repositories { ... } }`) should only be needed to add a compile (or runtime) dependency to the plugin (e.g. when used directly from the another plugin). Is that your case?

**Comment by marcphilipp** [comment]
`gradlePluginPortal()` is a shortcut if you want to use it as a regular dependency (e.g. in `buildSrc`).
