### ISSUE TITLE
Task :closeAndReleaseStagingRepository SKIPPED

### ISSUE THREAD

**Issue by andylamax** [gradle-nexus/publish-plugin#129]
Hello there,

Thank you for this amazing plugin.

For some strange reason, my artifacts are published to sonatype without a problem, but when it comes to closing and releasing the repository, nothing happens.

The task is skipped which now requires me to login to sonatype and close then release the repository manually.

Funny this is, sometimes in an another gradle module. It works as intended. Even closes and releases the repository.

Currently using version 1.1.0 of this plugin. What am I missing?

**Comment by szpak** [comment]
Some more context would be helpful. How do you call it? What is your project configuration (important places)? And what is the immediate output for the skipped task?

**Comment by andylamax** [comment]
The project is actually open source. 
> How do you call it?
I run the task ./gradlew publishToSonatype closeAndReleaseStagingRepository, as can be seen at https://github.com/aSoft-Ltd/mvivm/blob/f7ca4b46e8c4683607a2e4dc8dd80bc2939e8dff/.github/workflows/deploy.yml#L60

> What is your project configuration

A multi module project as it can be seen here https://github.com/aSoft-Ltd/mvivm/blob/master/settings.gradle.kts
But in summary

I have a project structure like this

| -- project root
    | -- live-core
    | -- live-react { dependsOn: live-core }
    | -- live-compose { dependsOn: live-core }
    | -- live-coroutines { dependsOn: live-core }
    | -- viewmodel-core { dependsOn: live-core }
    | -- viewmodel-react { dependsOn: viewmodel-core, live-react }
    | -- viewmodel-compose { dependsOn: viewmodel-compose, live-compose }
    | -- viewmodel-coroutines { dependsOn: viewmodel-coroutines, live-coroutines }
   
You can see the logs of the build here https://github.com/aSoft-Ltd/mvivm/runs/4318618320?check_suite_focus=true#step:10:2448

**Comment by szpak** [comment]
I don't see an immediate reason of being skipped - please re-run that releasing task with `--info`. 

Setting version in afterEvaluate might affect how the plugin resolves versions, however, you seem to also set version for the root project in `deployToSonatype {}`. In general, releasing multiproject Android projects is not fully supported - https://github.com/gradle-nexus/publish-plugin/issues/75 , so there could be some issues.

Nevertheless, I wonder, if you were able to previously release anything using this project, or it is your first try?

In the second, I propose to use just `closeStagingRepository` (instead of `closeAndReleaseStagingRepository`) to be able to manually inspect the prepared artifacts and drop them if there is something to be fixd (without releasing a - potentially - broken version to Maven Central).

**Comment by szpak** [comment]
@andylamax You haven't replied with more information, so I'm closing this issue. If you're still facing this problem feel free to re-open.
