### ISSUE TITLE
Failing "IvyNexusPublishPluginTests > can be used with lazily applied Gradle Plugin Development Plugin" on CI with LockTimeoutException

### ISSUE THREAD

**Issue by szpak** [gradle-nexus/publish-plugin#228]
The (compatibility) test "IvyNexusPublishPluginTests > can be used with lazily applied Gradle Plugin Development Plugin" failed twice on CI ([1](https://github.com/gradle-nexus/publish-plugin/actions/runs/5152744338/jobs/9279172923#step:4:216), [2](https://github.com/gradle-nexus/publish-plugin/actions/runs/5152865393/jobs/9280072186#step:4:222)) in short period of time. Both times on Mac and both times in the Ivy version (once with 7.6.1, once with 8.0.2) . The error in the output is not very helpful:

```
IvyNexusPublishPluginTests > can be used with lazily applied Gradle Plugin Development Plugin FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at DefaultGradleRunner.java:269
```

luckily, the [build scan](https://gradle.com/s/kgpvb2h4jwfbi) is more verbose:
```
> Task :initializeSonatypeStagingRepository	
Created staging repository 'orgexample-42' at http://localhost:49978/repositories/orgexample-42/content/	
	
> Task :gradle-plugin:generateDescriptorFileForFooPluginMarkerIvyPublication	
> Task :gradle-plugin:publishFooPluginMarkerIvyPublicationToSonatypeRepository	
> Task :gradle-plugin:generateDescriptorFileForPluginIvyPublication	
> Task :gradle-plugin:compileJava	
> Task :gradle-plugin:compileJava FAILED	
	
FAILURE: Build failed with an exception.	
	
* What went wrong:	
Execution failed for task ':gradle-plugin:compileJava'.	
> Could not resolve all files for configuration ':gradle-plugin:compileClasspath'.	
   > Timeout waiting to lock Generated Gradle JARs cache (/Users/runner/work/publish-plugin/publish-plugin/build/tmp/compatTest7.6.1/work/.gradle-test-kit/caches/7.6.1/generated-gradle-jars). It is currently in use by another Gradle instance.	
     Owner PID: 26887	
     Our PID: 26886	
     Owner Operation: 	
     Our operation: 	
     Lock file: /Users/runner/work/publish-plugin/publish-plugin/build/tmp/compatTest7.6.1/work/.gradle-test-kit/caches/7.6.1/generated-gradle-jars/generated-gradle-jars.lock	
	
* Try:	
> Run with --info or --debug option to get more log output.	
> Run with --scan to get full insights.	
	
* Exception is:	
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':gradle-plugin:compileJava'.	
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)	
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
...
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':gradle-plugin:compileClasspath'.
...
Caused by: org.gradle.cache.LockTimeoutException: Timeout waiting to lock Generated Gradle JARs cache (/Users/runner/work/publish-plugin/publish-plugin/build/tmp/compatTest7.6.1/work/.gradle-test-kit/caches/7.6.1/generated-gradle-jars). It is currently in use by another Gradle instance.	
Owner PID: 26887	
Our PID: 26886	
Owner Operation: 	
Our operation: 	
Lock file: /Users/runner/work/publish-plugin/publish-plugin/build/tmp/compatTest7.6.1/work/.gradle-test-kit/caches/7.6.1/generated-gradle-jars/generated-gradle-jars.lock	
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.timeoutException(DefaultFileLockManager.java:344)	
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lock(DefaultFileLockManager.java:305)	
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:164)
```

@maczikasz Do you think it is Ivy specific? Maybe you have any idea how to mitigate it?

**Comment by szpak** [comment]
Btw, it is possible to convince Gradle Test Kit to print more information about the error, in case of the execution failure?

**Comment by szpak** [comment]
After the recent merge, it [passed](https://github.com/gradle-nexus/publish-plugin/actions/runs/5211979017). Although, the macos and windows builds ar eway longer that the Linux one. In the past, the difference was not so much.
However, more things changes in the project (including changed Gradle version), so the reason can vary :-/.

**Comment by maczikasz** [comment]
hey @szpak I asked around, the answer I got is that chances are the error happens because the gradle distribution is being downloaded while another test is started in paralell. 
The mitigation strategies would be to either:

- Add a retry on the tests on CI
- Limit paralellism of tests to 1
- Run a single test of each gradle distribution before the main test task to prime the caches

**Comment by TWiStErRob** [comment]
I investigated this a bit, because it's really annoying that most branches fail CI.

I find it weird that the the `compatTest` tasks run one after the other:
https://scans.gradle.com/s/3deb6h3zjbpm6/timeline
![image](https://github.com/gradle-nexus/publish-plugin/assets/2906988/9817f25c-fb5d-48ee-bbba-fd19d15214fd)

I thought it was because `maxParallelForks = 8` takes up all the threads, so I removed that. To my surprise the build time halved!
![image](https://github.com/gradle-nexus/publish-plugin/assets/2906988/b02eeb57-cb61-404b-81e5-3c7e7a7d93e2)
Not what I was looking for, but I'll take it! Just for control, I re-added `maxParallelForks` and ran a similar setup as before, the build time doubled.

I [asked on Gradle `#performance` Slack](https://gradle-community.slack.com/archives/CALL1EXGT/p1689245609140659) and it was highlighted to me that `org.gradle.parallel` only really works on multimodule projects (i.e. inter-project parallelism). To get intra-project parallelism, we need to stop using the Project object in parallel, and Configuration Cache forces this. The end result:
![image](https://github.com/gradle-nexus/publish-plugin/assets/2906988/fdb12006-4e14-4fdb-9d18-b3e9a9a4e9e7)
throw on top of this the accidental improvement by maxParallelForks removal:
![image](https://github.com/gradle-nexus/publish-plugin/assets/2906988/67b53e96-e947-4e10-824d-5ade797c42a2)
and we have a winner: faster builds, and no flaky crash.

PR to follow.

**Comment by szpak** [comment]
Impressive results!
