### ISSUE TITLE
Error when running with Gradle `8.4`

### ISSUE THREAD

**Issue by DenuxPlays** [gradle-nexus/publish-plugin#282]
This error appears:
![image](https://github.com/gradle-nexus/publish-plugin/assets/83671398/999c2e3e-f4bf-4011-98d1-fd5980070546)

I dont know what gradle tries to say me hopefully someone here can help me

**Comment by TWiStErRob** [comment]
It's trying to say that your build produces signing artifacts that this plugin is trying to upload, but the build is not wired up to explicitly say this. This became a requirement I think in Gradle 8.0. See https://github.com/gradle-nexus/publish-plugin/issues/208, of which this issue seems to be a duplicate.

Based on a quick skim it seems that there's a missing reproducer still that ties the problem to this plugin specifically. Please have a read and try to provide one if possible.

If you want to continue upgrading your Gradle in the meantime, pick solution 2 as a workaround, something like:
```gradle
tasks.named(":publishReleasePublicationToSonatypeRepository").configure {
    dependsOn(":signArchives")
}
```

**Comment by DenuxPlays** [comment]
Thank you.
This worked for me:
```kotlin
//Fix for publishing with gradle 8.x
tasks.withType<PublishToMavenRepository>().configureEach {
    dependsOn(":signArchives")
}
```
