### ISSUE TITLE
Error of NexusRepository with the name provided already exists

### ISSUE THREAD

**Issue by mluizaa00** [gradle-nexus/publish-plugin#93]
Hello, I have been facing a error constantly while trying to use this plugin.

```
A problem occurred evaluating root project 'api'.
> Cannot add a NexusRepository with name 'kromaticsnapshots' as a NexusRepository with that name already exists.
```

I already modified the name multiple times and it continues to throw that problem.

Configuration:

```
nexusPublishing {
        repositories {
            kromaticsnapshots {
                snapshotRepositoryUrl = uri('https://repo.julianstaudt.de/repository/kromatic-snapshots/')
                username = System.getenv("KROMATIC_REPO_CI_USER") as String
                password = System.getenv("KROMATIC_REPO_CI_PASSWORD") as String
        }
    }
}
```

Publishing:

```
publishing {
        publications {
            bukkit(MavenPublication) { publication ->
                artifactId "kromatic-bukkit-api-$version"
                project.shadow.component(publication)
            }
        }
}
```

**Comment by szpak** [comment]
Are you sure you apply the GNPP plugin only in the root project?

**Comment by mluizaa00** [comment]
The plugin and nexus repository was applied to the root project, the publishing has been applied to the sub modules (A total of 3)
It is a regular project using JDK 11 and Gradle 7.0

**Comment by szpak** [comment]
I'm somehow puzzled. I would suspect that you also manually create that repository in the `publishing {}` block, but you don't.

Is it the only occurrence of `kromaticsnapshots` in your build configuration?

**Comment by mluizaa00** [comment]
That's correct. It's my first time using this plugin, I have tried also to change the repository name to something else then "kromaticsnapshots" but no luck.
The publications also have **different** names in each project, so that can't be the error too

**Comment by szpak** [comment]
I don't know what is the problem caused by. If that project is open source, please give me a link to it. If not, please remove all the code and dependencies to upload somewhere a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) project that reproduces the problem. Then, I will be able to debug it to get know why it happens.

Btw, you might also check with Gradle 6.8.3, but we have a basic regression tests with Gradle 7.0, so it shouldn't be a problem as well.

**Comment by mluizaa00** [comment]
Unfortunately the project is private but I was able to remove all the code and dependencies.
Here is the repository: https://github.com/mluizaa00/debug-nexus-plugin

Please let me know what you found debugging it, thank you for the help!

**Comment by szpak** [comment]
Thanks. And everything is clear now. That error was caused by the facts that the `nexusPublishing {}` block was placed inside the `allprojects {}` block. That triggers a try to create the aforementioned `kromaticsnapshots` multiple times. However, as distinct from publishing itself, the staging repository where the artifacts are created (and later released) is shared for all the modules and has to be defined once (in the root project for now). To solve it, simply move `nexusPublishing {}` outside.

It gave it a try locally and after the previous change it will fails with:
> Type 'InitializeNexusStagingRepository' property 'repository.nexusUrl' doesn't have a configured value.

That value is required. Even more, if you don't plan to release the project (just publish snapshots) our plugin is not needed. Otherwise, please set also `nexusUrl`, which should not be used for the snapshot versions.

Two more remarks. As the root project does not contain any code `allprojects {}` could be replaced with `subprojects {}`. Only `group` and `version` should be kept in the root project (as our plugin looks there for those values).

Please let me know, if it works for you.

**Comment by mluizaa00** [comment]
Thank you! That worked, but now my CI at Gitlab is having a error related to credentials:

```
A problem was found with the configuration of task ':api-bukkit:publishBukkitPublicationToKromaticRepository' (type 'PublishToMavenRepository').
  - Type 'PublishToMavenRepository' property 'credentials.username' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'credentials.username'.
      2. Mark property 'credentials.username' as optional.
```

The credentials username is currently a System environment variable already set in the machine that is executing the Gitlab, so that value isn't null

Also just to let you know, the CI executed the same thing but in Maven (We transferred everything from Maven to Gradle) so again it isn't possible the credentials doesn't exists

**Comment by szpak** [comment]
I have the same error, but with:

```
set -x KROMATIC_REPO_CI_USER x
./gradlew publish
```

it works (well, it fails with 401 Unauthorized, which is expect). Therefore, I would check if the values are in fact set in GitLab (maybe you run it as a merge request or from a not-protected branch)?

**Comment by mluizaa00** [comment]
Thank you very much! It finally worked because of your assist. 
I will be using this plugin for sure in the future

As help is no longer needed, this issue will be closed

**Comment by NeverMore93** [comment]
> 

same issue

**Comment by NeverMore93** [comment]
> Thank you! That worked, but now my CI at Gitlab is having a error related to credentials:
> 
> ```
> A problem was found with the configuration of task ':api-bukkit:publishBukkitPublicationToKromaticRepository' (type 'PublishToMavenRepository').
>   - Type 'PublishToMavenRepository' property 'credentials.username' doesn't have a configured value.
>     
>     Reason: This property isn't marked as optional and no value has been configured.
>     
>     Possible solutions:
>       1. Assign a value to 'credentials.username'.
>       2. Mark property 'credentials.username' as optional.
> ```
> 
> The credentials username is currently a System environment variable already set in the machine that is executing the Gitlab, so that value isn't null
> 
> Also just to let you know, the CI executed the same thing but in Maven (We transferred everything from Maven to Gradle) so again it isn't possible the credentials doesn't exists

same issue, any solution?
